// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-fDVUCvdtTUllAaoe20dYUN-Mvoc5JE',
    appId: '1:386168952752:web:0ab81a6f0f4a7eaa592875',
    messagingSenderId: '386168952752',
    projectId: 'flutter-notifications-inbox',
    authDomain: 'flutter-notifications-inbox.firebaseapp.com',
    storageBucket: 'flutter-notifications-inbox.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TQXt4W0JKGtRSP1qli3BuHOZuxC7aUw',
    appId: '1:386168952752:android:69ef85f83be8eadf592875',
    messagingSenderId: '386168952752',
    projectId: 'flutter-notifications-inbox',
    storageBucket: 'flutter-notifications-inbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3O7w6VukSqmY9k-tDMznm5BS64TKNhk',
    appId: '1:386168952752:ios:caf0f0b30ce77dff592875',
    messagingSenderId: '386168952752',
    projectId: 'flutter-notifications-inbox',
    storageBucket: 'flutter-notifications-inbox.appspot.com',
    iosClientId: '386168952752-32cr70entc065rfr22hi8odgc3g9cipv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotificationsInbox',
  );
}
